# Generated by Django 3.0 on 2021-09-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AllPeoduct',
            new_name='AllProduct',
        ),
    ]
