# Generated by Django 3.0 on 2021-09-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210925_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='imageurl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
