# Generated by Django 3.0 on 2021-10-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_allproduct_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproduct',
            name='instock',
            field=models.BooleanField(default=True),
        ),
    ]
