# Generated by Django 3.0 on 2021-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_orderlist_orderpending'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='sliptime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderpending',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
