# Generated by Django 3.0 on 2022-01-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20220110_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpending',
            name='trackingnumber',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
