# Generated by Django 3.1 on 2022-02-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20220212_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproduct',
            old_name='productid',
            new_name='id',
        ),
    ]
