# Generated by Django 3.1 on 2022-03-25 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0017_auto_20220212_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='orderid',
            new_name='deliverid',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='orderid',
            new_name='deliverid',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='user',
        ),
        migrations.AddField(
            model_name='delivery',
            name='ustomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.customer'),
        ),
    ]
