# Generated by Django 3.1 on 2022-03-25 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20220325_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='ustomer',
            new_name='customer',
        ),
    ]
