# Generated by Django 3.1 on 2022-03-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_remove_allproduct_imageurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
