# Generated by Django 3.1 on 2022-03-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20220326_0000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
