# Generated by Django 3.1 on 2022-03-26 00:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0023_delete_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Delivery',
            new_name='Order',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='user',
        ),
    ]
