# Generated by Django 3.1 on 2022-03-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20220326_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymentid',
        ),
    ]
