# Generated by Django 3.1 on 2022-03-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_remove_order_paymentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='productidname',
        ),
    ]
