# Generated by Django 4.1.5 on 2024-01-21 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
