# Generated by Django 4.1.5 on 2024-01-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
